name: Publish

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Common.sln
    - name: Build
      run: dotnet build ./src/Common.sln --no-restore -c Release -o ./Release
    - name: Get Version Number
      id: getversion
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: ./src/Common/Common.csproj
        xpath: /Project/PropertyGroup/Version
    - name: Publish Package
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: .src/Common/Common.csproj
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
