name: .NET

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Common.sln
    - name: Build
      run: dotnet build ./src/Common.sln --no-restore -c Release -o ./Release
    - name: Get Version Number
      id: getversion
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: ./src/Common/Common.csproj
        xpath: /Project/PropertyGroup/Version
    - name: Pack
      run: dotnet pack -v normal -c Release --no-restoure --include-symbols --include-source -p:PackageVersion=${{ steps.getversion.outputs.info }} ./src/Common/Common.csproj
    - name: Publish Package
      shell: pwsh 
      run: |
        dotnet nuget push ./Release/ShindigManager.Common.${{ steps.getversion.outputs.info }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Shindig-Manager/index.json
